config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "registrations",
    invitations: "invitations",
    sessions: "sessions"
  }
  devise_scope :user do
    put "/users/waitlist" => "invitations#waitlist"
    get "/sign_in" => "sessions#new"
  end

  root to: "home#index"
  get "/feed" => "home#feed"
  get "/search/users" => "search#users"
  get "/search/user_slyps" => "search#user_slyps"
  get "/search/friends" => "search#friends"
  get "/search/mutual_user_slyps" => "search#mutual_user_slyps"
  post "/persons/invite" => "persons#invite"
  get "/r/:referral_token" => "referrals#new"
  post "/r/capture" => "referrals#capture"
  get "/user_slyp/:id" => "user_slyps#show"
  put "/user_slyp/:id" => "user_slyps#update"
  put "/user_slyp/touch/:id" => "user_slyps#touch"
  post "/users/beta_request" => "users#beta_request"

  resources :persons, only: [:index, :show]
  resources :users, only: [:index]
  resources :friendships, only: [:create, :destroy]
  resources :user_slyps, only: [:create, :index]
  get "/reslyps/:id" => "reslyps#index"
  get "/reslyp/:id" => "reslyps#show"
  resources :reslyps, only: [:create, :destroy]
  resources :slyps, only: [:create]
  resources :replies, only: [:create, :update, :destroy, :show]
  get "/reslyp/replies/:id" => "replies#index"
  put "/user/:id" => "users#update"
  get "/user" => "users#index"
  resource :user

  if Rails.env.development?
    get "/rails/mailers" => "rails/mailers#index"
    get "/rails/mailers/*path" => "rails/mailers#preview"
  end
  # Make sure this is last
  get "*unmatched_route", to: redirect("/")
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  helper_method :resource_name, :resource, :devise_mapping

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def index
    return unless current_user && current_user.active?
    redirect_to "/feed"
  end

  def feed
    return redirect_to sign_in_url unless current_user
    return redirect_to accept_invitation_path unless current_user.active?
    @user = current_user
  end

  private

  # Cache/set invited_by_id as invite! method will set it to nil
  def accept_invitation_path
    inviter = User.find_by_id(current_user.invited_by_id)
    invitee = User.invite!({ email: current_user.email }, inviter) do |u|
      u.skip_invitation = true
    end
    attrs = { invitation_token: invitee.raw_invitation_token }
    Rails.application.routes.url_helpers
         .accept_user_invitation_path(invitee, attrs)
  end
end

app/views/home/feed.html.erb
<i id="close-left-pane" class="first floating-action big angle double left link icon" rv-class-share="appState.rightPaneActive" rv-show="appState.leftPaneActive" style="display:none;"></i>
<i id="open-conversations" class="second floating-action big talk outline link icon" rv-class-share="appState.rightPaneActive" rv-show="appState.leftPaneActive" style="font-size:1.6em;display:none;"></i>

<div id="js-sidebar-region" class="ui right very wide sidebar vertical menu">
  <%= render "home/backbone_templates/sidebar" %>
</div>

<div id="js-preview-sidebar-region" class="ui left sidebar vertical menu" rv-class-unless-fullscreen="appState.rightPaneActive" rv-class-majority-width="appState.rightPaneActive">
  <%= render "home/backbone_templates/preview_sidebar" %>
</div>

<div id="js-settings-sidebar-region" class="ui left fullscreen sidebar vertical menu">
  <%= render "home/backbone_templates/settings_sidebar" %>
</div>

<div class="pusher">
  <div id="js-nav-bar-region">
    <%= render "home/backbone_templates/nav_bar" %>
  </div>
  <div id="js-feed-region" style="background-color: #FAFAFA;">

  </div>
  <%= javascript_include_tag "feed" %>
  <%= render "home/backbone_templates/feed" %>
  <%= render "home/backbone_templates/slyp_card" %>
  <%= render "home/backbone_templates/reply" %>
  <%= render "home/backbone_templates/reslyp" %>
  <%= render "home/backbone_templates/no_persons_message" %>
  <%= render "home/backbone_templates/no_slyps_message" %>
  <%= render "home/backbone_templates/no_reslyps_message" %>
  <%= render "home/backbone_templates/onboarder_modal" %>
  <%= render "home/backbone_templates/preview_modal" %>
</div>

<div id="js-modals-region" class="ui dimmer modals page"></div>

<% if Rails.env.development? or Rails.env.staging? %>
  <script type="text/javascript">
    $('.ui.sidebar').sidebar({
      transition: 'overlay',
      onVisible: function(){
        if ($(window).width() < 769){
          $(this).removeClass('uncover').addClass('overlay');
        }
      }
    });
    rivets.bind($(document), { appState: slypApp.state });
  </script>
<% end %>

<script type="text/javascript">
  analytics.identify("<%= current_user.id %>", {
    display_name: "<%= current_user.display_name %>",
    email: "<%= current_user.email %>"
  }, {
    integrations: {
      Intercom : {
        user_hash : "<%= OpenSSL::HMAC.hexdigest("sha256", "lLRLl-zdG4rh_3-qA0Qr_Q5q2Zix8O9VSktLo6rl", current_user.id.to_s) %>"
      }
    }
  });
</script>

app/views/home/index.html.erb
<div class="full height image">
  <div class="ui main fluid container">
    <div class="ui basic segment">
      <button id="login" class="ui right floated basic black button">Login</button>
    </div>
    <div class="ui information container">
      <h1 class="ui center aligned header">slyp the share button</h1>
      <p>We are on a mission to make the Internet a less distracting, more engaging place. Enter your email below to join our limited beta program.</p>
      <div class="ui center aligned container" style="max-width: 400px !important;">
        <form id="beta-request">
          <div class="ui huge action fluid input">
            <input type="email" name="email" placeholder="Here's my email" autofocus>
            <button class="ui positive submit button">Thanks!</button>
          </div>
        </form>
      </div>
    </div>
  </div>

  <div class="ui vertical footer segment">
    <div class="ui center aligned container">
      <div class="ui horizontal inverted small divided link list">
        <a class="item" href="/users/sign_up">© 2016</a>
        <a class="item" href="#">Terms and Conditions</a>
        <a class="item" href="#">Privacy Policy</a>
      </div>
    </div>
  </div>
</div>

<div id="login-modal" class="ui modal">
  <div class="ui center aligned basic segment">
    <%= link_to user_facebook_omniauth_authorize_path do %>
      <button class="ui facebook big button">
        <i class="facebook icon"></i>
       Login with Facebook
      </button>
    <% end %>
  </div>
  <div class="ui horizontal divider">
    Or
  </div>
  <div class="ui grid">
    <div class="ui centered column">
      <%= form_for(resource, :as => resource_name, :url => session_path(:user), :class => "ui form") do |f| %>
        <div class="two fields">
          <div class="field">
            <div class="ui center aligned container">
              <div class="ui left icon input">
                <i class="user icon"></i>
                  <%= f.text_field :email, :placeholder => "my email" %>
              </div>
            </div>
          </div>
          <div class="field">
            <div class="ui center aligned container">
              <div class="ui left icon input">
                <i class="lock icon"></i>
                  <%= f.password_field :password, :placeholder => "top secret password" %>
              </div>
            </div>
          </div>
        </div>
        <div class="ui basic center aligned segment" style="padding-left: 15%;">
          <button class="ui large submit button">Login</button>
          <%= link_to "Forgot your password?", new_password_path(:user) %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div id="beta-success" class="ui small modal">
  <i class="close icon"></i>
  <div class="header">
    Thank you!
  </div>
  <div class="content">
     You are <span style="font-weight: bold;"></span> on the waitlist. We've sent you a welcome email and will be in touch with an invitiation shortly :)
  </div>
  <div class="actions">
    <button class="ui blue button">Got it</button>
  </div>
</div>

<div id="beta-error" class="ui small modal">
  <i class="close icon"></i>
  <div class="header">
  Hi again! :)
  </div>
  <div class="content">
    We see that you had already signed up for slyp beta, and we love and appreciate your enthusiasm. We will be in touch shortly with an invite.
  </div>
  <div class="actions">
    <button class="ui blue button">Got it</button>
  </div>
</div>

<%= javascript_include_tag "home" %>